f1 = open ("file.txt" , "r")
content = f1.read()
f1.seek(0)
print(content)
line1 = f1.readline()
line2 = f1.readline()
line3 = f1.readline()
f1.seek(0)
lines = f1.readlines()
print(lines)
print(line3)
print(f1.tell())
f1.seek(0)
print(f1.tell())
f1.seek(0,2)
print(f1.tell())
f1.close()